package controller.command;

public enum CommandType {
    LOGIN_PAGE,
    LOGOUT,
    LOGIN,
    INSPECTOR_REPORT_LIST,
    CLIENT_REPORT_LIST,
    LANGUAGE_CHANGE,
    REPORT_PAGE,
    CREATE_REPORT,
    VIEW_PAGE,
    ADD_COMMENT_AND_STATUS,
    INSPECTOR_CABINET,
    CLIENT_CABINET,
    INSPECTOR_REPORT_VIEW,
    CLIENT_REPORT_VIEW
}
